'use client';

import React, { useState, useEffect } from 'react';
import { ShoppingCart, ChefHat, Check, ArrowRight, Sparkles, Users, ChevronDown, ChevronUp, ExternalLink, Leaf, Printer, Loader2, Utensils, Star, Search } from 'lucide-react';

// --- ALGORITHM Helpers ---
const generateShoppingList = (plan: any[], peopleCount: number) => {
  const list: any = {};
  
  plan.forEach((recipe: any) => {
    const scaleFactor = peopleCount / (recipe.servings || 4);

    recipe.ingredients.forEach((ing: any) => {
      const scaledAmount = ing.amount * scaleFactor;

      if (!list[ing.name]) {
        list[ing.name] = { 
          name: ing.name,
          totalAmount: scaledAmount, 
          unit: ing.unit, 
          category: ing.category, 
          emoji: ing.emoji || '🥘', 
          recipes: [recipe.title],
          count: 1 
        };
      } else {
        if (list[ing.name].unit === ing.unit) {
          list[ing.name].totalAmount += scaledAmount;
        }
        list[ing.name].count += 1;
        list[ing.name].recipes.push(recipe.title);
      }
    });
  });

  return Object.values(list).sort((a: any, b: any) => a.category.localeCompare(b.category));
};

const formatAmount = (amount: number) => {
  if (amount % 1 === 0) return amount;
  return amount.toFixed(1).replace('.0', '');
};

// Helper to extract domain name for display
const getDomain = (url: string) => {
  try {
    const domain = new URL(url).hostname;
    return domain.replace('www.', '').split('.')[0]; // e.g. "allrecipes"
  } catch (e) {
    return 'Web';
  }
};

// --- SUBCOMPONENTS ---

const RecipeCard = ({ recipe, peopleCount }: { recipe: any; peopleCount: number }) => {
  const [expanded, setExpanded] = useState(false);
  const scaleFactor = peopleCount / (recipe.servings || 4);

  const handlePrint = (e: any) => {
    e.stopPropagation(); 
    const printWindow = window.open('', '_blank', 'width=800,height=600');
    if (!printWindow) return;

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>${recipe.title}</title>
          <style>
            body { font-family: 'Georgia', serif; padding: 40px; color: #1c1917; max-width: 800px; margin: 0 auto; }
            .header { border-bottom: 2px solid #047857; padding-bottom: 20px; margin-bottom: 30px; }
            h1 { color: #064e3b; font-size: 28px; margin: 0 0 10px 0; }
            .meta { color: #57534e; font-style: italic; font-size: 14px; }
            h3 { margin-top: 25px; color: #047857; font-family: sans-serif; font-size: 16px; text-transform: uppercase; letter-spacing: 1px; }
            .ingredients-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px 40px; margin-bottom: 30px; }
            .ingredient-item { border-bottom: 1px solid #e7e5e4; padding: 8px 0; }
            ol { line-height: 1.6; margin-left: 20px; }
            li { margin-bottom: 12px; padding-left: 10px; }
            @media print { body { padding: 0; } button { display: none; } }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>${recipe.title}</h1>
            <div class="meta">${recipe.description}</div>
            <div class="meta" style="margin-top: 5px;"><strong>Serves:</strong> ${peopleCount} people</div>
          </div>
          <h3>Ingredients</h3>
          <div class="ingredients-grid">
            ${recipe.ingredients.map((ing: any) => `
              <div class="ingredient-item">
                ${ing.emoji || ''} <strong>${formatAmount(ing.amount * scaleFactor)} ${ing.unit}</strong> ${ing.name}
              </div>
            `).join('')}
          </div>
          <h3>Instructions</h3>
          <ol>${recipe.instructions.map((step: string) => `<li>${step}</li>`).join('')}</ol>
          <div style="margin-top: 50px; text-align: center; font-size: 12px; color: #a8a29e;">Generated by Laissez-faire</div>
          <script>window.onload = function() { window.print(); }</script>
        </body>
      </html>
    `;
    printWindow.document.write(htmlContent);
    printWindow.document.close();
  };

  // Smart Link Logic
  const hasRealLink = recipe.sourceUrl && recipe.sourceUrl.startsWith('http');
  const finalLink = hasRealLink ? recipe.sourceUrl : `https://www.google.com/search?q=${encodeURIComponent(recipe.title + " Recipe")}`;
  const linkText = hasRealLink ? `View on ${getDomain(recipe.sourceUrl)}` : "Find Recipe";
  const LinkIcon = hasRealLink ? ExternalLink : Search;

  return (
    <div className={`bg-white rounded-2xl shadow-sm border border-stone-200 transition-all duration-300 overflow-hidden ${expanded ? 'ring-2 ring-emerald-100 shadow-md' : 'hover:border-emerald-300'}`}>
      <div onClick={() => setExpanded(!expanded)} className="cursor-pointer">
        {/* Image Banner */}
        <div className="w-full h-32 sm:h-48 overflow-hidden relative bg-stone-100 group">
            {recipe.imageUrl ? (
              <img 
                  src={recipe.imageUrl} 
                  alt={recipe.title}
                  className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-700"
                  loading="lazy"
              />
            ) : (
              <div className="w-full h-full flex items-center justify-center bg-stone-200 text-stone-400">
                <ChefHat size={48} opacity={0.2} />
              </div>
            )}
            
            <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/60 to-transparent p-4 pt-12">
                <h4 className="font-bold text-lg text-white leading-tight shadow-black drop-shadow-md">{recipe.title}</h4>
            </div>
        </div>

        <div className="p-4 flex justify-between items-start">
            <div className="flex-1">
                <div className="flex items-center gap-2 mb-2">
                    {recipe.kidFriendly && <span className="text-[10px] font-bold uppercase text-orange-600 bg-orange-100 px-2 py-0.5 rounded-full">Kid Safe</span>}
                    <div className="flex items-center gap-1 text-xs font-semibold text-amber-500">
                        <Star size={12} fill="currentColor" />
                        <span>{recipe.rating || 4.5}</span>
                        <span className="text-stone-400 font-normal">({recipe.reviewCount || 120})</span>
                    </div>
                </div>
                <p className="text-stone-500 text-sm line-clamp-2">{recipe.description}</p>
            </div>
            <div className="ml-4 text-stone-400 mt-1">
            {expanded ? <ChevronUp size={20} /> : <ChevronDown size={20} />}
            </div>
        </div>
      </div>

      {expanded && (
        <div className="px-6 pb-6 border-t border-stone-100 bg-stone-50/50 animate-in slide-in-from-top-2 duration-200">
          <div className="mt-4 mb-6">
            <h5 className="text-xs font-bold text-stone-400 uppercase tracking-wider mb-3">Ingredients ({peopleCount} servings)</h5>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
              {recipe.ingredients.map((ing: any, i: number) => (
                <div key={i} className="flex items-center justify-between text-sm p-2 bg-white rounded-lg border border-stone-100">
                  <span className="text-stone-700 flex items-center gap-2">
                    <span>{ing.emoji}</span>
                    {ing.name}
                  </span>
                  <span className="font-semibold text-emerald-700">
                    {formatAmount(ing.amount * scaleFactor)} <span className="text-xs text-stone-400 font-normal">{ing.unit}</span>
                  </span>
                </div>
              ))}
            </div>
          </div>
          <div className="mb-6">
             <h5 className="text-xs font-bold text-stone-400 uppercase tracking-wider mb-3">Instructions</h5>
             <ol className="space-y-3 list-decimal list-inside text-sm text-stone-700 marker:text-emerald-600 marker:font-bold">
               {recipe.instructions.map((step: string, i: number) => <li key={i} className="pl-1 leading-relaxed">{step}</li>)}
             </ol>
          </div>
          <div className="pt-4 border-t border-stone-200 flex justify-between items-center">
            <button onClick={handlePrint} className="flex items-center gap-2 text-xs font-bold text-stone-500 hover:text-emerald-700 px-3 py-1.5 rounded-md hover:bg-stone-100 transition-colors">
              <Printer size={14} /> Print Recipe
            </button>
            
            {/* SMART LINK BUTTON */}
            <a href={finalLink} target="_blank" rel="noreferrer" className="flex items-center gap-1 text-xs font-bold text-blue-600 hover:underline bg-blue-50 px-3 py-1.5 rounded-md hover:bg-blue-100 transition-colors">
              {linkText} <LinkIcon size={12} />
            </a>
          </div>
        </div>
      )}
    </div>
  );
};

// --- MAIN APP ---

export default function LaissezFaireApp() {
  const [step, setStep] = useState('input'); 
  const [mealCount, setMealCount] = useState(3);
  const [peopleCount, setPeopleCount] = useState(1); 
  const [kidFriendly, setKidFriendly] = useState(false);
  const [cuisine, setCuisine] = useState('Mediterranean');
  const [priority, setPriority] = useState('Balanced'); 
  const [isLoading, setIsLoading] = useState(false);
  const [statusText, setStatusText] = useState('');
  
  const [plan, setPlan] = useState<any[]>([]);
  const [shoppingList, setShoppingList] = useState<any[]>([]);

  const handlePlan = async () => {
    setIsLoading(true);
    
    const messages = [
        "Consulting Chef...", 
        "Searching the web for recipes...", 
        "Finding best matches...",
        "Scraping images...", 
        "Finalizing shopping list..."
    ];
    let msgIndex = 0;
    setStatusText(messages[0]);
    
    const intervalId = setInterval(() => {
        msgIndex = (msgIndex + 1) % messages.length;
        setStatusText(messages[msgIndex]);
    }, 2000);

    try {
      const response = await fetch('/api/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ 
          count: mealCount, 
          people: peopleCount,
          diet: cuisine,
          kidFriendly,
          priority 
        })
      });

      const newRecipes = await response.json();

      if (Array.isArray(newRecipes)) {
        setPlan(newRecipes);
        setShoppingList(generateShoppingList(newRecipes, peopleCount));
        setStep('results');
      } else {
        console.error("Invalid format received", newRecipes);
      }
    } catch (e) {
      console.error("Failed to generate", e);
    } finally {
      clearInterval(intervalId);
      setIsLoading(false);
      setStatusText('');
    }
  };

  const reset = () => {
    setStep('input');
    setPlan([]);
    setShoppingList([]);
  };

  // Custom Print Function for Shopping List Only
  const printShoppingList = () => {
    const printWindow = window.open('', '_blank', 'width=600,height=800');
    if (!printWindow) return;

    const html = `
        <html>
            <head>
                <title>Shopping List - Laissez-faire</title>
                <style>
                    body { font-family: sans-serif; padding: 30px; color: #333; }
                    h1 { color: #047857; border-bottom: 2px solid #047857; padding-bottom: 10px; }
                    .meta { margin-bottom: 20px; color: #666; font-size: 14px; }
                    .item { display: flex; justify-content: space-between; padding: 8px 0; border-bottom: 1px solid #eee; }
                    .name { font-weight: bold; }
                    .amount { color: #047857; }
                    .category { font-size: 12px; color: #999; margin-top: 2px;}
                    @media print { button { display: none; } }
                </style>
            </head>
            <body>
                <h1>Shopping List</h1>
                <div class="meta">For ${plan.length} meals • Serving ${peopleCount} person${peopleCount > 1 ? 's' : ''}</div>
                
                ${shoppingList.map(item => `
                    <div class="item">
                        <div>
                            <div class="name">${item.emoji || ''} ${item.name}</div>
                            <div class="category">${item.category}</div>
                        </div>
                        <div class="amount">${formatAmount(item.totalAmount)} ${item.unit}</div>
                    </div>
                `).join('')}

                <div style="margin-top: 40px; text-align: center; font-size: 12px; color: #ccc;">Generated by Laissez-faire</div>
                <script>window.onload = function() { window.print(); }</script>
            </body>
        </html>
    `;
    printWindow.document.write(html);
    printWindow.document.close();
  };

  return (
    <div className="min-h-screen bg-stone-50 text-stone-900 font-sans selection:bg-emerald-200 pb-20">
      
      {/* Header */}
      <header className="bg-white border-b border-stone-200 sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 bg-emerald-700 rounded-full flex items-center justify-center text-white shadow-sm">
              <Leaf size={16} strokeWidth={2.5} />
            </div>
            <span className="font-serif font-bold text-xl sm:text-2xl tracking-tight text-emerald-900">Laissez-faire</span>
          </div>
          {step === 'results' && (
            <button onClick={reset} className="text-sm font-medium text-stone-500 hover:text-emerald-700">
              Start Over
            </button>
          )}
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-8">
        
        {step === 'input' ? (
          <div className="flex flex-col items-center justify-center min-h-[60vh] animate-in fade-in slide-in-from-bottom-4 duration-500">
            <div className="text-center mb-10 space-y-2">
              <h1 className="text-4xl font-serif font-bold text-stone-800">What's the plan?</h1>
              <p className="text-lg text-stone-500">I'll plan. You cook.</p>
            </div>

            <div className="w-full max-w-md bg-white rounded-2xl shadow-xl shadow-stone-200 border border-stone-100 p-8 space-y-8">
              
              {/* Cuisine Selection */}
              <div className="space-y-3">
                <label className="block text-xs font-bold text-stone-400 uppercase tracking-wider">Cuisine</label>
                <div className="relative">
                  <select 
                    value={cuisine}
                    onChange={(e) => setCuisine(e.target.value)}
                    className="w-full p-3 pl-4 pr-10 text-lg bg-stone-50 border-2 border-stone-200 rounded-xl focus:border-emerald-500 focus:outline-none transition-colors text-stone-700 font-medium appearance-none cursor-pointer hover:border-emerald-300"
                  >
                    <option value="Mediterranean">Mediterranean Diet</option>
                    <option value="Italian">Italian</option>
                    <option value="Mexican">Mexican</option>
                    <option value="Asian Stir-Fry">Asian Stir-Fry</option>
                    <option value="Classic American">Classic American</option>
                    <option value="Cajun / Creole">Cajun / Creole</option>
                    <option value="Thai">Thai</option>
                    <option value="Indian">Indian</option>
                    <option value="Greek">Greek</option>
                    <option value="Japanese">Japanese</option>
                    <option value="French">French</option>
                    <option value="Vegetarian">Vegetarian</option>
                    <option value="Keto">Keto Friendly</option>
                    <option value="Paleo">Paleo</option>
                  </select>
                  <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-stone-400 pointer-events-none" size={20} />
                </div>
              </div>

              {/* Priority Selection */}
              <div className="space-y-3">
                <label className="block text-xs font-bold text-stone-400 uppercase tracking-wider">Prioritize</label>
                <div className="relative">
                  <select 
                    value={priority}
                    onChange={(e) => setPriority(e.target.value)}
                    className="w-full p-3 pl-4 pr-10 text-lg bg-stone-50 border-2 border-stone-200 rounded-xl focus:border-emerald-500 focus:outline-none transition-colors text-stone-700 font-medium appearance-none cursor-pointer hover:border-emerald-300"
                  >
                    <option value="Balanced">Balanced (Default)</option>
                    <option value="Cheaper Ingredients">Cheaper Ingredients</option>
                    <option value="Fewer Ingredients">Fewer Ingredients (Easy Prep)</option>
                    <option value="Fancier Meals">Fancier Meals</option>
                  </select>
                  <ChevronDown className="absolute right-4 top-1/2 -translate-y-1/2 text-stone-400 pointer-events-none" size={20} />
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
                  {/* Meal Counter */}
                  <div className="space-y-3">
                    <label className="block text-xs font-bold text-stone-400 uppercase tracking-wider">Dinners</label>
                    <div className="flex items-center justify-between bg-stone-50 border-2 border-stone-200 rounded-xl p-1">
                      <button 
                        onClick={() => setMealCount(Math.max(1, mealCount - 1))}
                        className="w-12 h-12 flex items-center justify-center bg-white rounded-lg shadow-sm border border-stone-200 text-stone-600 hover:bg-stone-100 text-xl font-bold active:scale-95 transition-all"
                      >
                        -
                      </button>
                      <div className="flex items-center gap-2 px-2">
                        <Utensils size={18} className="text-emerald-700/50" />
                        <span className="text-3xl font-serif font-black text-emerald-700">{mealCount}</span>
                      </div>
                      <button 
                        onClick={() => setMealCount(Math.min(7, mealCount + 1))}
                        className="w-12 h-12 flex items-center justify-center bg-emerald-700 rounded-lg shadow-sm text-white hover:bg-emerald-800 text-xl font-bold active:scale-95 transition-all"
                      >
                        +
                      </button>
                    </div>
                  </div>

                  {/* People Counter */}
                  <div className="space-y-3">
                    <label className="block text-xs font-bold text-stone-400 uppercase tracking-wider">People</label>
                    <div className="flex items-center justify-between bg-stone-50 border-2 border-stone-200 rounded-xl p-1">
                      <button 
                        onClick={() => setPeopleCount(Math.max(1, peopleCount - 1))}
                        className="w-12 h-12 flex items-center justify-center bg-white rounded-lg shadow-sm border border-stone-200 text-stone-600 hover:bg-stone-100 text-xl font-bold active:scale-95 transition-all"
                      >
                        -
                      </button>
                      <div className="flex items-center gap-2 px-2">
                        <Users size={18} className="text-emerald-700/50" />
                        <span className="text-3xl font-serif font-black text-emerald-700">{peopleCount}</span>
                      </div>
                      <button 
                        onClick={() => setPeopleCount(Math.min(12, peopleCount + 1))}
                        className="w-12 h-12 flex items-center justify-center bg-emerald-700 rounded-lg shadow-sm text-white hover:bg-emerald-800 text-xl font-bold active:scale-95 transition-all"
                      >
                        +
                      </button>
                    </div>
                  </div>
              </div>

              {/* Kid Friendly Toggle */}
              <div 
                onClick={() => setKidFriendly(!kidFriendly)}
                className={`cursor-pointer group flex items-center justify-between p-4 rounded-xl border-2 transition-all duration-200 ${kidFriendly ? 'border-orange-400 bg-orange-50' : 'border-stone-200 hover:border-stone-300'}`}
              >
                <div className="flex items-center gap-3">
                  <div className={`p-2 rounded-full ${kidFriendly ? 'bg-orange-100 text-orange-600' : 'bg-stone-100 text-stone-400'}`}>
                    <Sparkles size={20} />
                  </div>
                  <div>
                    <div className={`font-bold ${kidFriendly ? 'text-orange-700' : 'text-stone-700'}`}>Kid-Friendly Mode</div>
                    <div className="text-xs text-stone-500">Simple flavors, no spicy food</div>
                  </div>
                </div>
                <div className={`w-6 h-6 rounded-full border-2 flex items-center justify-center transition-colors ${kidFriendly ? 'bg-orange-500 border-orange-500' : 'border-stone-300'}`}>
                  {kidFriendly && <Check size={14} className="text-white" />}
                </div>
              </div>

              {/* Action Button */}
              <div className="space-y-3">
                <button 
                    onClick={handlePlan}
                    disabled={isLoading}
                    className="w-full py-4 bg-stone-900 text-white rounded-xl font-bold text-lg shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all flex items-center justify-center gap-2 disabled:opacity-50 disabled:hover:translate-y-0"
                >
                    {isLoading ? (
                    <>
                        <Loader2 className="animate-spin" size={20} />
                        Generating...
                    </>
                    ) : (
                    <>
                        <ChefHat size={20} />
                        Generate Plan
                    </>
                    )}
                </button>
                
                {/* Status Line */}
                <div className="h-6 text-center">
                    {isLoading && (
                        <p className="text-xs font-medium text-emerald-600 animate-pulse">{statusText}</p>
                    )}
                </div>
              </div>

            </div>
          </div>
        ) : (
          <div className="animate-in slide-in-from-right-8 duration-500 space-y-12">
            
            {/* Intro */}
            <div className="flex items-center justify-between">
               <div>
                  <h2 className="text-2xl font-serif font-bold text-stone-900">Your Menu</h2>
                  <p className="text-stone-500">Calculated for <strong className="text-stone-900">{peopleCount} person{peopleCount > 1 ? 's' : ''}</strong>.</p>
               </div>
               <div className="text-right hidden sm:block">
                  <div className="text-3xl font-black text-emerald-700">{plan.length}</div>
                  <div className="text-xs font-bold uppercase text-stone-400 tracking-wider">Meals</div>
               </div>
            </div>

            {/* Two Column Layout */}
            <div className="grid lg:grid-cols-12 gap-8">
              
              {/* Left Col: Recipes (7 cols) */}
              <div className="lg:col-span-7 space-y-4">
                <div className="flex items-center gap-2 mb-2">
                  <ChefHat className="text-emerald-700" size={20} />
                  <h3 className="text-lg font-bold text-stone-800">Recipes</h3>
                </div>
                
                {plan.map((recipe: any, idx: number) => (
                  <RecipeCard key={idx} recipe={recipe} peopleCount={peopleCount} />
                ))}
              </div>

              {/* Right Col: Shopping List (5 cols) */}
              <div className="lg:col-span-5 space-y-6">
                <div className="flex items-center gap-2 mb-4">
                  <ShoppingCart className="text-emerald-700" size={20} />
                  <h3 className="text-lg font-bold text-stone-800">Shopping List</h3>
                </div>

                <div className="bg-white rounded-2xl shadow-lg border border-stone-200 overflow-hidden sticky top-24">
                  <div className="p-4 bg-stone-50 border-b border-stone-200">
                    <p className="text-xs font-semibold text-stone-500 uppercase tracking-wider">Amounts for {peopleCount} Person{peopleCount > 1 ? 's' : ''}</p>
                  </div>
                  <div className="divide-y divide-stone-100 max-h-[calc(100vh-250px)] overflow-y-auto">
                    {shoppingList.length === 0 ? (
                        <div className="p-8 text-center text-stone-400">No items found.</div>
                    ) : (
                        shoppingList.map((item: any, i: number) => (
                            <a 
                                key={i}
                                href={`https://www.walmart.com/search?q=${encodeURIComponent(item.name)}`}
                                target="_blank"
                                rel="noreferrer"
                                className="flex items-start justify-between p-4 hover:bg-emerald-50 transition-colors group cursor-pointer text-left"
                            >
                                <div className="flex items-start gap-3">
                                    <div className="mt-1 w-4 h-4 rounded border border-stone-300 group-hover:border-emerald-500 group-hover:bg-emerald-500 transition-colors flex items-center justify-center flex-shrink-0">
                                        <ArrowRight size={10} className="text-white opacity-0 group-hover:opacity-100" />
                                    </div>
                                    <div>
                                        <div className="font-medium text-sm text-stone-900 group-hover:text-emerald-800 transition-colors leading-tight">{item.name}</div>
                                        <div className="text-[10px] text-stone-400 mt-1">
                                            Used in {item.count} meal{item.count > 1 ? 's' : ''}
                                        </div>
                                    </div>
                                </div>
                                <div className="text-xs font-bold text-stone-600 bg-stone-100 px-2 py-1 rounded-md group-hover:bg-white whitespace-nowrap ml-2">
                                    {formatAmount(item.totalAmount)} {item.unit}
                                </div>
                            </a>
                        ))
                    )}
                  </div>
                  <div className="p-4 bg-stone-50 border-t border-stone-200 text-center">
                    <button onClick={printShoppingList} className="flex items-center justify-center gap-2 w-full py-2 text-sm font-bold text-emerald-700 hover:bg-emerald-100 rounded-lg transition-colors">
                        <Printer size={16} /> Print Shopping List
                    </button>
                  </div>
                </div>
              </div>

            </div>
          </div>
        )}
      </main>
    </div>
  );
}
